// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxkzsztzhdjmzxjynliv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4a3pzenR6aGRqbXp4anlubGl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODc3MzMsImV4cCI6MjA3MTk2MzczM30.QJ3B5C_oE75-E9rugRIdNR7hf1CFDpnAIy1wCBfQPWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});